### приветствие
GET http://localhost:8080/calculator/
Content-Type: application/json

### +
GET http://localhost:8080/calculator/plus?num1=5&num2=5
Content-Type: application/json

### -
GET http://localhost:8080/calculator/minus?num1=5&num2=5
Content-Type: application/json

### *
GET http://localhost:8080/calculator/multiply?num1=5
Content-Type: application/json

### /
GET http://localhost:8080/calculator/divide?num1=5&num2=0
Content-Type: application/json